"""
Main script for running the Hybrid On-Device tnGPS experiments.
This script orchestrates the experiments using train.py, evaluate.py, and preprocess.py.
"""

import os
import sys
import numpy as np
import torch
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from config.experiment_config.config import *

from src.preprocess import setup_environment
from src.train import LightweightTNSS, FullScaleLLM
from src.evaluate import (
    run_iterations, evaluate_candidate, candidate_generation_baseline,
    candidate_generation_hybrid, candidate_generation_with_finetuning
)

sns.set(style="whitegrid")

def experiment_resource_profiling(device, n_iter=PROFILING_ITERATIONS):
    """
    Experiment 1:
    Compare the lightweight on-device TN-SS model and the full-scale LLM baseline in terms of runtime and memory.
    """
    print("Starting Experiment 1: Efficiency and Resource Profiling on Constrained Hardware")
    
    light_model = LightweightTNSS()
    full_model = FullScaleLLM()
    
    print("Running iterations for the lightweight model...")
    t_light, mem_light, mem_usage_light = run_iterations(light_model, device, n_iter)
    print("Running iterations for the full-scale model (baseline)...")
    t_full, mem_full, mem_usage_full = run_iterations(full_model, device, n_iter)
    
    print("Results:")
    print(f"Lightweight Model    - Time: {t_light:.3f}s, Avg Memory: {mem_light:.2f} MB")
    print(f"Full-Scale Model     - Time: {t_full:.3f}s, Avg Memory: {mem_full:.2f} MB")
    
    iterations = np.arange(n_iter)
    
    plt.figure(figsize=(8, 4))
    plt.plot(iterations, mem_usage_light, label="Lightweight Model", linewidth=2)
    plt.plot(iterations, mem_usage_full, label="Full-Scale Model", linestyle='--', linewidth=2)
    plt.xlabel("Iteration")
    plt.ylabel("Memory Usage (MB)")
    plt.title("Memory Usage Comparison")
    plt.legend()
    plt.tight_layout()
    plt.savefig(f"{LOGS_DIR}/memory_usage_comparison.pdf")
    plt.close()
    print(f"Experiment 1 plot saved as {LOGS_DIR}/memory_usage_comparison.pdf\n")

def experiment_quality_comparison(n_iter=QUALITY_ITERATIONS):
    """
    Experiment 2:
    Compare the quality of candidates generated by the baseline full-scale model versus the hybrid on-device TN-SS method.
    """
    print("Starting Experiment 2: Comparative Quality of Candidate Generation")
    light_model = LightweightTNSS()
    full_model = FullScaleLLM()
    
    print("Generating candidate quality metrics for baseline (full-scale LLM)...")
    baseline_qualities = candidate_generation_baseline(full_model, n_iter)
    print("Generating candidate quality metrics for hybrid method (lightweight + teacher refinement)...")
    hybrid_qualities = candidate_generation_hybrid(light_model, full_model, refine_every=REFINE_EVERY, n_iter=n_iter)
    
    iterations = np.arange(n_iter)
    plt.figure(figsize=(8, 4))
    plt.plot(iterations, baseline_qualities, label="Baseline (Full LLM)", linewidth=2)
    plt.plot(iterations, hybrid_qualities, label="Hybrid On-Device tnGPS", linestyle='--', linewidth=2)
    plt.xlabel("Iteration")
    plt.ylabel("Candidate Quality (Simulated Metric)")
    plt.title("Candidate Quality Generation Comparison")
    plt.legend()
    plt.tight_layout()
    plt.savefig(f"{LOGS_DIR}/quality_evolution_comparison.pdf")
    plt.close()
    print(f"Quality evolution plot saved as {LOGS_DIR}/quality_evolution_comparison.pdf")
    
    t_stat, p_value = stats.ttest_rel(hybrid_qualities, baseline_qualities)
    print(f"Paired t-test results: T-statistic = {t_stat:.3f}, p-value = {p_value:.3f}\n")

def experiment_finetuning_efficacy(n_iter=FINETUNING_ITERATIONS):
    """
    Experiment 3:
    Compare candidate quality evolution with and without lightweight fine-tuning that incorporates
    simulated domain feedback.
    """
    print("Starting Experiment 3: Lightweight Fine-Tuning and Domain Feedback Loop Efficacy")
    light_model = LightweightTNSS()
    teacher_model = FullScaleLLM()
    
    print("Generating candidate quality metrics without fine-tuning (baseline using full LLM) ...")
    candidate_qualities_no_ft = candidate_generation_baseline(teacher_model, n_iter)
    print("Generating candidate quality metrics with on-device fine-tuning (simulated feedback) ...")
    candidate_qualities_ft = candidate_generation_with_finetuning(light_model, teacher_model, refine_every=REFINE_EVERY, n_iter=n_iter)
    
    iterations = np.arange(n_iter)
    plt.figure(figsize=(8, 4))
    plt.plot(iterations, candidate_qualities_no_ft, label="Without Fine-Tuning (Baseline)", linewidth=2)
    plt.plot(iterations, candidate_qualities_ft, label="With On-Device Fine-Tuning", linestyle='--', linewidth=2)
    plt.xlabel("Iteration")
    plt.ylabel("Candidate Quality (Simulated Metric)")
    plt.title("Impact of Lightweight Fine-Tuning with Domain Feedback")
    plt.legend()
    plt.tight_layout()
    plt.savefig(f"{LOGS_DIR}/quality_finetuning_comparison.pdf")
    plt.close()
    print(f"Fine-tuning efficacy plot saved as {LOGS_DIR}/quality_finetuning_comparison.pdf\n")

def test_experiments():
    """
    Run a quick version of each experiment to test that the code is executed correctly.
    Each test runs for a short number of iterations.
    """
    device = setup_environment()
    
    print("Running quick tests for all experiments...\n")
    test_iter = TEST_ITERATIONS
    
    print("=== Testing Resource Profiling (Experiment 1) ===")
    experiment_resource_profiling(device, n_iter=test_iter)
    
    print("=== Testing Candidate Quality Comparison (Experiment 2) ===")
    experiment_quality_comparison(n_iter=test_iter)
    
    print("=== Testing Fine-Tuning Efficacy (Experiment 3) ===")
    experiment_finetuning_efficacy(n_iter=test_iter)
    
    print("All quick tests completed successfully.")

if __name__ == '__main__':
    device = setup_environment()
    
    experiment_resource_profiling(device, n_iter=PROFILING_ITERATIONS)
    experiment_quality_comparison(n_iter=QUALITY_ITERATIONS)
    experiment_finetuning_efficacy(n_iter=FINETUNING_ITERATIONS)
    
    
    print("All experiments finished successfully.")
